
title: Hentie Paxton Profile
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Hentie Paxton  ## put your name
title: 'Full Stack Senior Developer'  ## your title
location: Randburg, South Africa, 2188

## Social Profiles
facebook: https://www.facebook.com/hentie.paxton  ## your facebook account url
twitter: https://twitter.com/HentiePaxton  ## your twitter account url
linkedin: https://www.linkedin.com/in/hentie-paxton-42646776/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
